"""Camada de persistência do totem.

Usa SQLite (stdlib) para armazenar **produtos**, **movimentações de estoque**
e **vendas** realizadas no totem. O catálogo é sincronizado a partir do ERP
**Sankhya** (``database.erp`` + ``erp_sync.py``), para onde também vão clientes e
pedidos; o estoque operacional é gerido no painel administrativo.

Os símbolos públicos são reexportados aqui para manter ``from database import ...``.

Esquema (resumo)
----------------

- ``products`` — catálogo (sku, preço, categoria, imagem, estoque, mínimo, ativo).
- ``stock_movements`` — variações de estoque (entrada, saída, venda).
- ``transactions`` / ``transaction_items`` — pedidos e itens com snapshot.
- ``sellers`` — credenciais dos vendedores.
- ``events`` / ``event_products`` / ``event_sellers`` — inventário por evento.
- ``erp_settings`` / ``erp_payment_types`` / ``erp_customers`` / ``erp_outbox`` /
  ``erp_sync_runs`` — integração Sankhya (configuração, tipos de negociação,
  CPF → CODPARC, fila de pedidos e histórico de sincronizações).

Invariante: toda alteração de ``products.stock`` é feita na mesma conexão
que insere a ``stock_movements`` correspondente.
"""
from __future__ import annotations

from .promotions import (
    RULE_TYPE_LABELS,
    active_promotion_names_by_product_id,
    active_promotion_tooltip_by_product_id,
    build_promo_display_map,
    create_promotion,
    delete_promotion,
    enrich_product_with_promo,
    get_active_promotions_for_event,
    get_promotion,
    list_promotions_for_event,
    list_promotions_for_event_export,
    product_ids_with_active_promotions_for_event,
    quote_cart_items_for_event,
    toggle_promotion_active,
    update_promotion,
)
from .gifts import (
    GIFT_RULE_LABELS,
    active_gift_rules_for_cart,
    create_gift_item,
    create_gift_rule,
    delete_gift_item,
    delete_gift_rule,
    get_gift_item,
    get_gift_rule,
    list_gift_items_for_event,
    list_gift_rules_for_event,
    toggle_gift_rule_active,
    update_gift_item,
    update_gift_rule,
)
from .badges import (
    event_badge_fg_hex,
    event_badge_style_pairs,
    normalize_event_badge_color,
)
from .checkout_holds import (
    list_checkout_stock_conflicts,
    release_seller_checkout_holds,
    sync_seller_checkout_holds,
)
from .customers import (
    CUSTOMER_SORTS,
    DEFAULT_CUSTOMER_SORT,
    find_customer_by_cpf,
    get_customer_display_name,
    get_customer_profile,
    get_portfolio_analytics,
    list_customers,
)
from .connection import DB_PATH, DEFAULT_MIN_STOCK, get_conn
from .seller_analytics import get_seller_analytics, list_seller_events
from .events import (
    EXPORT_MOVEMENTS_CSV_CAP,
    EXPORT_SALES_ITEMS_CSV_CAP,
    EXPORT_SALES_SUMMARY_CSV_CAP,
    EXPORT_STOCK_CSV_CAP,
    add_product_to_event,
    add_seller_to_event,
    archive_event,
    count_event_products_filtered,
    create_event,
    delete_event,
    EVENT_OPERATION_TYPES,
    event_operation_noun,
    event_operation_type_label,
    find_product_by_sku_or_id,
    get_event_financial_report,
    get_event_goal_progress,
    get_active_event_for_seller,
    get_event,
    get_event_sales_analytics,
    get_event_sales_dashboard,
    get_event_stats,
    get_event_stock_stats,
    get_seller_admin_event_selection_id,
    list_active_event_product_stocks,
    list_event_products,
    list_event_products_filtered_for_client,
    list_event_products_for_client,
    list_event_products_slice,
    list_event_sellers,
    list_events,
    list_transaction_items_for_event_period,
    list_transactions_summary_for_event_period,
    normalize_event_operation_type,
    remove_product_from_event,
    replace_seller_event_assignment,
    restore_event,
    set_event_operations_closed,
    event_ops_open,
    update_event,
    update_event_goals,
    update_event_product_backorder_limit,
    update_event_product_price,
    update_event_product_stock,
)
from .event_stock import (
    list_event_stock_movements,
    register_event_stock_adjustment,
    register_event_stock_entry,
    register_event_stock_exit,
)
from .products import (
    count_products_admin_filtered,
    get_product,
    get_product_in_event,
    is_unsellable_variant_parent,
    list_active_product_stocks,
    list_distinct_product_categories,
    list_products_admin,
    list_products_admin_slice,
    list_products_for_client,
    prepare_catalog_variant_groups,
    summarize_catalog_option_groups,
    retire_unsellable_variant_parents,
    set_product_active,
    get_product_erp_link_summary,
    product_awaiting_erp_price,
    set_product_erp_codprod,
    set_product_erp_codvol,
    upsert_products_from_erp,
    update_product_min_stock,
    update_product_price,
    variant_children_preview,
)
from .schema import init_db
from .sellers import (
    create_seller_account,
    delete_seller,
    ensure_seller_account,
    get_seller,
    get_seller_by_email,
    get_seller_by_username,
    list_seller_pin_hashes,
    list_sellers,
    list_sellers_without_codvend,
    normalize_seller_codvend,
    update_seller_account,
    update_seller_last_login,
    validate_seller_username,
)
from .stock import (
    count_stock_movements,
    get_product_events_stock_total,
    get_products_library_stats,
    get_stock_stats,
    list_stock_movements,
    max_stock_movement_id_filtered,
    register_stock_adjustment,
    register_stock_entry,
    register_stock_exit,
)
from .transactions import (
    cancel_pending_transaction,
    cancel_pending_transaction_for_seller,
    confirm_item_delivery,
    confirm_items_delivery,
    confirm_transaction_handover,
    confirm_transaction_with_aut,
    count_event_product_ledger,
    count_pending_delivery_transactions,
    count_transactions_for_event,
    count_transactions_for_seller,
    create_transaction,
    generate_order_number,
    get_pending_transaction_if_owned,
    get_pending_transaction_restore_payload,
    get_stats,
    get_transaction,
    get_transaction_by_order_number,
    list_event_product_ledger,
    list_transactions,
    list_transactions_for_event,
    list_transactions_for_seller,
    pending_delivery_units_by_product_for_event,
    units_sold_by_product_for_event,
    units_sold_by_product_for_seller,
    refund_transaction,
    replace_transaction_item_product,
    reset_totem_to_default_state,
    update_pending_transaction,
    update_transaction_receipt_note,
)

__all__ = [
    "RULE_TYPE_LABELS",
    "active_promotion_names_by_product_id",
    "active_promotion_tooltip_by_product_id",
    "build_promo_display_map",
    "create_promotion",
    "delete_promotion",
    "enrich_product_with_promo",
    "get_active_promotions_for_event",
    "get_promotion",
    "list_promotions_for_event",
    "list_promotions_for_event_export",
    "product_ids_with_active_promotions_for_event",
    "quote_cart_items_for_event",
    "toggle_promotion_active",
    "update_promotion",
    "GIFT_RULE_LABELS",
    "active_gift_rules_for_cart",
    "create_gift_item",
    "create_gift_rule",
    "delete_gift_item",
    "delete_gift_rule",
    "get_gift_item",
    "get_gift_rule",
    "list_gift_items_for_event",
    "list_gift_rules_for_event",
    "update_gift_item",
    "toggle_gift_rule_active",
    "update_gift_rule",
    "EXPORT_MOVEMENTS_CSV_CAP",
    "EXPORT_SALES_ITEMS_CSV_CAP",
    "EXPORT_SALES_SUMMARY_CSV_CAP",
    "EXPORT_STOCK_CSV_CAP",
    "DB_PATH",
    "DEFAULT_MIN_STOCK",
    "add_product_to_event",
    "add_seller_to_event",
    "archive_event",
    "cancel_pending_transaction",
    "cancel_pending_transaction_for_seller",
    "confirm_item_delivery",
    "confirm_items_delivery",
    "confirm_transaction_handover",
    "confirm_transaction_with_aut",
    "count_event_product_ledger",
    "count_pending_delivery_transactions",
    "count_event_products_filtered",
    "count_products_admin_filtered",
    "count_stock_movements",
    "count_transactions_for_event",
    "count_transactions_for_seller",
    "create_event",
    "delete_event",
    "EVENT_OPERATION_TYPES",
    "event_operation_noun",
    "event_operation_type_label",
    "get_event_financial_report",
    "get_event_goal_progress",
    "create_seller_account",
    "create_transaction",
    "delete_seller",
    "ensure_seller_account",
    "event_badge_fg_hex",
    "event_badge_style_pairs",
    "find_product_by_sku_or_id",
    "generate_order_number",
    "get_active_event_for_seller",
    "get_conn",
    "CUSTOMER_SORTS",
    "DEFAULT_CUSTOMER_SORT",
    "find_customer_by_cpf",
    "get_customer_display_name",
    "get_customer_profile",
    "get_portfolio_analytics",
    "list_customers",
    "get_seller_analytics",
    "list_seller_events",
    "get_event",
    "get_event_sales_analytics",
    "get_event_sales_dashboard",
    "get_event_stats",
    "get_event_stock_stats",
    "get_pending_transaction_if_owned",
    "get_pending_transaction_restore_payload",
    "get_product",
    "get_product_events_stock_total",
    "get_product_in_event",
    "get_products_library_stats",
    "get_seller",
    "get_seller_admin_event_selection_id",
    "get_seller_by_email",
    "get_seller_by_username",
    "get_stats",
    "get_stock_stats",
    "get_transaction",
    "get_transaction_by_order_number",
    "init_db",
    "is_unsellable_variant_parent",
    "list_checkout_stock_conflicts",
    "list_active_event_product_stocks",
    "list_active_product_stocks",
    "list_distinct_product_categories",
    "list_event_product_ledger",
    "list_event_products",
    "list_event_products_filtered_for_client",
    "list_event_products_for_client",
    "list_event_products_slice",
    "list_event_sellers",
    "list_event_stock_movements",
    "list_events",
    "list_products_admin",
    "list_products_admin_slice",
    "list_products_for_client",
    "prepare_catalog_variant_groups",
    "summarize_catalog_option_groups",
    "list_seller_pin_hashes",
    "list_sellers",
    "list_stock_movements",
    "list_transaction_items_for_event_period",
    "list_transactions",
    "list_transactions_for_event",
    "list_transactions_for_seller",
    "list_transactions_summary_for_event_period",
    "max_stock_movement_id_filtered",
    "normalize_event_badge_color",
    "normalize_event_operation_type",
    "pending_delivery_units_by_product_for_event",
    "units_sold_by_product_for_event",
    "units_sold_by_product_for_seller",
    "release_seller_checkout_holds",
    "refund_transaction",
    "replace_transaction_item_product",
    "register_event_stock_adjustment",
    "register_event_stock_entry",
    "register_event_stock_exit",
    "register_stock_adjustment",
    "register_stock_entry",
    "register_stock_exit",
    "remove_product_from_event",
    "replace_seller_event_assignment",
    "reset_totem_to_default_state",
    "restore_event",
    "set_event_operations_closed",
    "event_ops_open",
    "set_product_active",
    "sync_seller_checkout_holds",
    "get_product_erp_link_summary",
    "product_awaiting_erp_price",
    "set_product_erp_codprod",
    "set_product_erp_codvol",
    "upsert_products_from_erp",
    "variant_children_preview",
    "update_event",
    "update_event_goals",
    "update_event_product_backorder_limit",
    "update_event_product_price",
    "update_event_product_stock",
    "update_pending_transaction",
    "update_transaction_receipt_note",
    "update_product_min_stock",
    "update_product_price",
    "update_seller_account",
    "list_sellers_without_codvend",
    "normalize_seller_codvend",
    "update_seller_last_login",
    "validate_seller_username",
]

